(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(column-number-mode t)
 '(custom-enabled-themes '(nano-light))
 '(custom-safe-themes
   '("db5b906ccc66db25ccd23fc531a213a1afb500d717125d526d8ff67df768f2fc" "f0eb51d80f73b247eb03ab216f94e9f86177863fb7e48b44aacaddbfe3357cf1" default))
 '(display-time-mode t)
 '(electric-pair-mode t)
 '(font-use-system-font nil)
 '(global-display-line-numbers-mode t)
 '(menu-bar-mode nil)
 '(org-blank-before-new-entry '((heading) (plain-list-item)))
 '(org-fontify-done-headline nil)
 '(org-fontify-todo-headline nil)
 '(package-selected-packages
   '(bm rustic dired-hide-dotfiles dired-filetype-face dired-single nano-theme vterm-toggle olivetti dimmer dashboard vterm eshell-git-prompt company lsp-julia lsp-pyright org-roam captain rainbow-delimiters which-key mixed-pitch writeroom-mode company-box lsp-mode visual-fill-column org-bullets helpful doom-modeline doom-themes magit))
 '(save-place-mode t)
 '(scroll-bar-mode nil)
 '(scroll-conservatively 100)
 '(show-paren-mode t)
 '(size-indication-mode t)
 '(tool-bar-mode nil)
 '(widget-image-enable nil)
 '(window-divider-default-bottom-width 1)
 '(window-divider-default-places t)
 '(window-divider-mode t)
 '(x-underline-at-descent-line t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(bm-fringe-persistent-face ((t (:background "lemon chiffon" :foreground "black"))))
 '(bm-persistent-face ((t (:background "lemon chiffon" :foreground "black"))))
 '(dired-filetype-execute ((t (:foreground "red"))))
 '(dired-filetype-image ((t (:foreground "gray47"))))
 '(dired-filetype-plain ((t (:foreground "gold4"))))
 '(dired-filetype-source ((t (:foreground "chocolate"))))
 '(dired-filetype-video ((t (:foreground "gainsboro"))))
 '(dired-filetype-xml ((t (:foreground "dark cyan"))))
 '(italic ((t (:inherit nano-faded :slant italic))))
 '(ivy-org ((t (:inherit org-level-1))))
 '(markdown-header-face-1 ((t (:height 1.1 :foreground "#8b4513"))))
 '(markdown-header-face-2 ((t (:height 1.08 :foreground "#cd661d"))))
 '(markdown-header-face-3 ((t (:height 1.05 :foreground "#ee7621"))))
 '(markdown-header-face-4 ((t (:height 1.03 :foreground "#ff7f24"))))
 '(markdown-header-face-5 ((t (:foreground "#ff7f24"))))
 '(nano-modeline-active-status-RO ((t (:inherit (nano-subtle nano-strong) :background "#D8E0E6" :foreground "white"))))
 '(org-block ((t (:inherit fixed-pitch))))
 '(org-block-begin-line ((t (:height 100))))
 '(org-block-end-line ((t (:height 100))))
 '(org-code ((t (:inherit (shadow fixed-pitch)))))
 '(org-document-info ((t (:height 100))))
 '(org-document-info-keyword ((t (:height 100))))
 '(org-document-title ((t (:height 140 :weight bold))))
 '(org-drawer ((t (:height 100))))
 '(org-level-1 ((t (:height 1.1 :foreground "#8b4513"))))
 '(org-level-2 ((t (:height 1.08 :foreground "#cd661d"))))
 '(org-level-3 ((t (:height 1.05 :foreground "#ee7621"))))
 '(org-level-4 ((t (:height 1.03 :foreground "#ff7f24"))))
 '(org-level-5 ((t (:foreground "#ff7f24"))))
 '(org-link ((t (:underline t))))
 '(org-meta-line ((t (:height 100))))
 '(org-property-value ((t (:height 100))) t)
 '(org-special-keyword ((t (:height 100))))
 '(org-tag ((t (:height 100))))
 '(org-verbatim ((t (:inherit fixed-pitch))))
 '(window-divider ((t (:foreground "#ECEFF1"))))
 '(window-divider-first-pixel ((t (:foreground "#ECEFF1"))))
 '(window-divider-last-pixel ((t (:foreground "#ECEFF1")))))
