(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["#2e3436" "#a40000" "#4e9a06" "#c4a000" "#204a87" "#5c3566" "#729fcf" "#eeeeec"])
 '(column-number-mode t)
 '(cursor-type 'bar)
 '(custom-enabled-themes '(nano-dark))
 '(custom-safe-themes
   '("3c83b3676d796422704082049fc38b6966bcad960f896669dfc21a7a37a748fa" "98fada4d13bcf1ff3a50fceb3ab1fea8619564bb01a8f744e5d22e8210bfff7b" "f0eb51d80f73b247eb03ab216f94e9f86177863fb7e48b44aacaddbfe3357cf1" "37768a79b479684b0756dec7c0fc7652082910c37d8863c35b702db3f16000f8" "db5b906ccc66db25ccd23fc531a213a1afb500d717125d526d8ff67df768f2fc" default))
 '(dimmer-adjustment-mode :foreground)
 '(display-time-mode t)
 '(electric-pair-mode t)
 '(font-use-system-font nil)
 '(fringe-mode 0 nil (fringe))
 '(global-display-line-numbers-mode t)
 '(menu-bar-mode nil)
 '(nano-modeline-prefix 'default)
 '(nano-modeline-prefix-padding t)
 '(olivetti-margin-width 7)
 '(olivetti-minimum-body-width 90)
 '(olivetti-style 'fancy)
 '(org-blank-before-new-entry '((heading) (plain-list-item)))
 '(org-fontify-done-headline nil)
 '(org-fontify-todo-headline nil)
 '(package-selected-packages
   '(centered-cursor-mode selectric-mode ox-pandoc buffer-flip julia-repl yasnippet flyspell-correct-ivy nord-theme emojify nano-theme vterm-toggle olivetti bm dired-hide-dotfiles dired-filetype-face dired-single dimmer vterm company rustic cargo lsp-julia org-roam captain rainbow-delimiters ivy-prescient which-key mixed-pitch writeroom-mode company-box lsp-mode visual-fill-column org-bullets helpful doom-modeline doom-themes magit))
 '(save-place-mode t)
 '(scroll-bar-mode nil)
 '(scroll-conservatively 100)
 '(show-paren-mode t)
 '(size-indication-mode t)
 '(tool-bar-mode nil)
 '(visible-bell t)
 '(widget-image-enable nil)
 '(window-divider-default-bottom-width 1)
 '(window-divider-default-places t)
 '(window-divider-default-right-width 5)
 '(window-divider-mode t)
 '(x-underline-at-descent-line t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#000000" :foreground "#ECEFF4" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 111 :width normal :foundry "JB" :family "JetBrains Mono NL"))))
 '(bm-fringe-persistent-face ((t (:background "#4C566A"))))
 '(bm-persistent-face ((t (:background "#4C566A"))))
 '(cursor ((t (:background "#EBCB8B" :foreground "#2E3440"))))
 '(dashboard-items-face ((t (:inherit widget-button :foreground "#F4E0BD"))))
 '(dired-filetype-execute ((t (:foreground "red"))))
 '(dired-filetype-image ((t (:foreground "gray47"))))
 '(dired-filetype-plain ((t (:foreground "gold4"))))
 '(dired-filetype-source ((t (:foreground "chocolate"))))
 '(dired-filetype-video ((t (:foreground "gainsboro"))))
 '(dired-filetype-xml ((t (:foreground "dark cyan"))))
 '(flyspell-incorrect ((t (:inherit highlighted :underline (:color "red" :style wave)))))
 '(font-lock-builtin-face ((t (:inherit nano-salient))))
 '(font-lock-constant-face ((t (:inherit nano-salient))))
 '(font-lock-doc-face ((t (:inherit nano-faded :foreground "#ebcb8b"))))
 '(font-lock-function-name-face ((t (:inherit nano-strong :foreground "#8FBCBB"))))
 '(font-lock-keyword-face ((t (:inherit (nano-salient nano-strong)))))
 '(font-lock-negation-char-face ((t (:foreground "orange red"))))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face :foreground "#8fbcbb"))))
 '(font-lock-string-face ((t (:inherit nano-faded :foreground "#a3be8c"))))
 '(font-lock-type-face ((t (:inherit nano-strong :foreground "#81A1C1"))))
 '(font-lock-variable-name-face ((t (:inherit nano-strong :foreground "#F4E0BD"))))
 '(italic ((t (:inherit nano-faded :slant italic))))
 '(ivy-org ((t (:inherit org-level-1))))
 '(line-number ((t (:inherit nil :foreground "#A3BE8C"))))
 '(line-number-current-line ((t (:inherit nano-strong :foreground "#ADE979"))))
 '(markdown-header-face-1 ((t (:height 1.1 :foreground "#8b4513"))))
 '(markdown-header-face-2 ((t (:height 1.08 :foreground "#cd661d"))))
 '(markdown-header-face-3 ((t (:height 1.05 :foreground "#ee7621"))))
 '(markdown-header-face-4 ((t (:height 1.03 :foreground "#ff7f24"))))
 '(markdown-header-face-5 ((t (:foreground "#ff7f24"))))
 '(nano-modeline-active-status-RO ((t (:inherit (nano-subtle nano-strong) :background "#BF616A" :foreground "#434C5E"))))
 '(nano-modeline-active-status-RW ((t (:inherit (nano-faded-i nano-strong) :background "#a3be8c"))))
 '(nano-modeline-inactive ((t (:inherit nano-subtle-i))))
 '(nano-popout ((t (:foreground "#EBCB8B"))) t)
 '(nano-popout-i ((t (:background "#EBCB8B" :foreground "#2E3440"))) t)
 '(nano-salient ((t (:foreground "#B48EAD"))) t)
 '(nano-salient-i ((t (:background "#B48EAD" :foreground "#2E3440"))) t)
 '(nano-strong ((t (:foreground "#FFFFFF" :weight bold))) t)
 '(nano-subtle ((t (:background "#76A0BC"))) t)
 '(nano-subtle-i ((t (:foreground "#76A0BC"))) t)
 '(olivetti-fringe ((t (:background "gray18"))))
 '(org-block ((t (:inherit fixed-pitch))))
 '(org-block-begin-line ((t (:height 100))))
 '(org-block-end-line ((t (:height 100))))
 '(org-code ((t (:inherit (shadow fixed-pitch)))))
 '(org-date ((t (:background "#88C0D0" :foreground "#242424" :slant oblique :weight ultra-bold :height 0.95))))
 '(org-document-info ((t (:height 100))))
 '(org-document-info-keyword ((t (:height 100))))
 '(org-document-title ((t (:height 140 :weight bold))))
 '(org-drawer ((t (:inherit nano-faded :height 100))))
 '(org-ellipsis ((t (:inherit nano-strong))))
 '(org-level-1 ((t (:inherit default :extend nil :foreground "#bf616a" :height 1.4))))
 '(org-level-2 ((t (:inherit nano-strong :extend nil :foreground "#d08770" :height 1.2))))
 '(org-level-3 ((t (:inherit nano-strong :extend nil :foreground "#ebcb8b" :height 1.15))))
 '(org-level-4 ((t (:inherit nano-strong :extend nil :foreground "#a3be8c" :height 1.1))))
 '(org-level-5 ((t (:foreground "#ff7f24"))))
 '(org-link ((t (:underline t))))
 '(org-meta-line ((t (:inherit nano-faded :height 0.8))))
 '(org-property-value ((t (:height 100))) t)
 '(org-remark-highlighter ((t (:background "#EBCB8B" :foreground "black" :underline "tan1"))))
 '(org-special-keyword ((t (:height 100))))
 '(org-table ((t (:inherit nano-popout))))
 '(org-tag ((t (:height 100))))
 '(org-verbatim ((t (:inherit fixed-pitch))))
 '(region ((t (:inherit nil :extend t :background "#677691"))))
 '(window-divider ((t (:inherit nano-modeline-inactive))))
 '(window-divider-first-pixel ((t (:inherit window-divider))))
 '(window-divider-last-pixel ((t (:inherit window-divider)))))
